spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true   # system.out을 통해서 출력
        format_sql: true
        default_batch_fetch_size : 100

logging:
  level:
    org.hibernate.SQL: debug   # logger를 통해서 출력. 운영환경에서는 logger를 통해 찍어야함.
    org.hibernate.type: trace   # 파라미터 확인용